export const mockPlayers: any = [
  {
    id: '1',
    name: 'Oscar',
    vote: 1,
    userType: 'player',
    userRole: 'player',
    visible: false,
    position: '',
  },
  {
    id: '2',
    name: 'Vane',
    vote: 1,
    userType: 'player',
    userRole: 'player',
    visible: false,
    position: '',
  },
  {
    id: '3',
    name: 'Sarah',
    vote: 1,
    userType: 'player',
    userRole: 'player',
    visible: false,
    position: '',
  },
  {
    id: '4',
    name: 'Kiara',
    vote: 1,
    userType: 'player',
    userRole: 'player',
    visible: false,
    position: '',
  },
  {
    id: '5',
    name: 'Pedro',
    vote: 1,
    userType: 'player',
    userRole: 'player',
    visible: false,
    position: '',
  },
  {
    id: '6',
    name: 'Ana',
    vote: 1,
    userType: 'player',
    userRole: 'player',
    visible: false,
    position: '',
  },
  {
    id: '7',
    name: 'Carlos',
    vote: 1,
    userType: 'player',
    userRole: 'player',
    visible: false,
    position: '',
  },
];

export const cards = [0, 1, 3, 5, 8, 13, 21, '?', '☕️'];
